### ISSUE TITLE
ChunkLoad Error when uploading a pdf from local file system.

### ISSUE THREAD

**Issue by jhashekhar** [jhashekhar/pspdfkit-web-example-react#2]
### Description

What we want to do involves the first step to upload a blank pdf. For that we made a simple react component with a input field that takes in a file type for upload [code here](https://github.com/jhashekhar/pspdfkit-web-example-react/blob/upload-test/src/components/pspdfkit/index.js).

It leads to the following error:
<img width="1680" alt="issue-ss2" src="https://user-images.githubusercontent.com/17599212/148337318-5449cd14-54ff-4bf0-82b5-0ff36c9c513c.png">

We believe it has something to do with Request URL under the Headers:
Normally its -> `http://localhost:3000/pspdfkit-lib/chunk-6401-4539497b278c7054.js`

But when we do the upload pdf, it tries to fetch from:
It fetches from this url -> `http://localhost:3000/static/js/pspdfkit-lib/chunk-6401-4539497b278c7054.js`
(you can see this in the inspector at the bottom of the above image)

### How to Replicate the issue
The modification to code is minimal. Only a new file in the `src/components/pspdfkit` has been added, its named `index.js`.

So the replication is pretty straightforward:

Clone the repo
```
git clone https://github.com/jhashekhar/pspdfkit-web-example-react.git
cd pspdfkit-web-example-react
```
Install the project dependencies with npm:
`npm install`

Run the app.
`npm run start`

Finally, click on the upload button on the rendered webpage at localhost and try uploading any pdf from your local file system.

**Comment by jhashekhar** [comment]
@nicholaspoz @Frank-vdm Please check this out. Thanks!

**Comment by nicholaspoz** [comment]
This is great @jhashekhar ! The only thing I'll add is 
1. we are trying to upload a local pdf by following [the guide here](https://pspdfkit.com/guides/web/open-a-document/from-local-storage/) (see "you want to let the user select a file from the local file system...")
2. We think the [`baseUrl` defined in App.js](https://github.com/jhashekhar/pspdfkit-web-example-react/blob/master/src/App.js#L5) is not being respected by chunk loading based on [the guidance here](https://github.com/jhashekhar/pspdfkit-web-example-react#react-component)

**Comment by jhashekhar** [comment]
This issue has been resolved. The upload feature is working after the solution suggested in the response from PSPDF team!

**Comment by jhashekhar** [comment]
This issue has been resolved. The upload feature is working after the solution suggested in the response from PSPDF team!
